name: End to End Test
'on':
  workflow_dispatch:
    inputs:
      PROJECT_NAME:
        description: Project Name
      PROJECT_DESCRIPTION:
        description: Project description
      CLOUD_PROVIDER:
        description: Cloud Provider
      ACCESS_KEY:
        description: Access Key
      SECRET_KEY:
        description: Secret Key
      ENERGY_LEAKS_URL:
        description: Project URL for Energy Leaks
      ENERGY_LEAKS_BRANCH:
        description: Branch for Energy Leaks
      ML_JOB_CONSUMPTION_CODE_URL:
        description: Code URL for ML Job Consumption
      ENERGY_METRICS_SERVER_IP:
        description: Server IP for Energy Metrics
  schedule:
  - cron: '1 13 * * 1-5 '
  push:
    branches:
    - '!master'
    - development
    - main
jobs:
  Non-master:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Non-master
      run: '#!/bin/bash'
      
  Development:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
    - name: Development
      run: echo "Building for development branch" 
           echo "second line"
           echo "third line"
      
  checkoutCode:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: DaggupatiPavan/java-web-app-docker
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: 'echo "Building for development branch"; echo "second line"; echo "third line"'

  release:
    runs-on: ubuntu-latest
    steps:
    - name: Release
      run: |
        echo "releasing update"
  approval:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
    - name: Await Manual Approval
      run: echo "Approval required. Approve this job to continue."
  setUpSsh:
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH
      run: |
        echo "running set up SSH"
      # uses: webfactory/ssh-agent@v0.5.3
      # with:
        # ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  runCommandsOverSsh:
    runs-on: ubuntu-latest
    steps:
    - name: Run Commands over SSH
      run: |
        echo "running commands over ssh"
      # ssh -o StrictHostKeyChecking=no user@hostname "your-remote-command"
  syncToS3:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to S3
      run: |
        echo "running s3 sync"

      # aws s3 sync ./sync s3://${S3_BUCKET_NAME}/ --delete --region ${REGION}'
  uploadArtifact:
    runs-on: ubuntu-latest
    steps:
    - name: creating a file
      run: |
        echo "artifact file" > output.pdf
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my_artifact
        path: output.pdf
    
