name: CI/CD Pipeline
'on':
  workflow_dispatch:
    inputs:
      Generation:
        description: Intel processor generation
      Optimization:
        description: Use Intel optimized instance type or not
        type: choice
        options:
        - Optimized
        - Non-Optimized
      InstanceType:
        description: EC2 instance type to provision
      OS:
        description: Operating system for the EC2 instance
        type: choice
        options:
        - Ubuntu
      DB:
        description: Select DB
        type: choice
        options:
        - Postgres
        - MySQL
      Harness:
        description: Select Harness
        type: choice
        options:
        - HammerDB
      VolumeType:
        description: EBS volume type
        type: choice
        options:
        - gp2
        - gp3
        - io1
        - io2
        - sc1
        - st1
        - standard
      VolumeSize:
        description: Size of EBS volume in GB
        type: choice
        options:
        - '50'
        - '100'
        - '150'
        - '200'
