name: Deploy Workflow
 
on:
  workflow_dispatch:
    inputs:
      selectedRegion:
        description: 'AWS Region for deployment'
        required: false
        type: choice
        options:
          - us-east-1
          - us-west-1
          - eu-west-1
 
jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    outputs:
      selectedRegion: ${{ steps.set-region.outputs.selectedRegion }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - name: Run Initial Steps
        run: echo "Running pre-deployment tasks..."
 
      - name: Request Region Input
        if: ${{ github.event.inputs.selectedRegion == '' }}
        run: |
          echo "Please select a region and re-run the workflow."
          exit 1  # This forces the workflow to stop until the user provides input.
 
  deploy:
    needs: pre-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        run: echo "Deploying to AWS region ${{ github.event.inputs.selectedRegion }}"
