name: Testing Inputs
on: 
  workflow_dispatch:
    inputs:
      choice_inputs:
        description: Select one choice parameter
        type: choice
        options:
        - option 1
        - option 2
        - option 3
  
      string_inputs:
        description: give the string input
        required: true
        default: default_value_added
  
      boolean_inputs:
        description: boolen value input given
        required: false
        type: 'boolean'
    
