name: CI/CD Pipeline
on:
  push:
    branches:
    - main
  schedule:
  - cron: '1 13 * * * 1-5 '
jobs:
  Checkout code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: DaggupatiPavan/java-web-app-docker
  Create an EC2 Instance:
    runs-on: ubuntu-latest
    steps:
    - name: Create an EC2 Instance
      run: '#!/bin/bash

        terraform init

        terraform validate

        terraform plan

        terraform apply --auto-approve'
  Install K8s and Docker:
    runs-on: ubuntu-latest
    steps:
    - name: Install K8s and Docker
      run: "#!/bin/bash\nIP_ADDRESSES=$(terraform output instance_ip | jq -r)\n  \
        \                      > myinventory\n                        echo \"auctane\
        \ ansible_ssh_host=ubuntu@${IP_ADDRESSES}\" >> myinventory\n             \
        \           cat myinventory\nansible-playbook -i myinventory ks8_install.yaml\n\
        \                    ansible-playbook -i myinventory docker.yaml"
  Build Docker Image:
    runs-on: ubuntu-latest
    steps:
    - name: Build Docker Image
      run: '#!/bin/bash

        docker build -t 10.63.16.153:32003/ubiq:${BUILD_NUMBER} .'
  Log in to Docker Hub:
    runs-on: ubuntu-latest
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  Push Docker Image:
    runs-on: ubuntu-latest
    steps:
    - name: Push Docker Image
      run: '#!/bin/bash

        docker push 10.63.16.153:32003/ubiq:${BUILD_NUMBER}'
  Deploy to Kubernetes:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Kubernetes
      run: "#!/bin/bash\nIP_ADDRESSES=$(terraform output instance_ip | jq -r)\n  \
        \                  ansible-playbook -i myinventory deploy.yaml\n         \
        \           ssh ubuntu@${IP_ADDRESSES} \"kubectl create secret docker-registry\
        \ regcred --docker-server=http://10.63.12.180:32003 --docker-username=admin\
        \ --docker-password=admin\"\n                    ssh ubuntu@${IP_ADDRESSES}\
        \ \"kubectl apply -f pod.yaml\"\n                    ssh ubuntu@${IP_ADDRESSES}\
        \ \"kubectl expose pod ubiq --type=NodePort --port=80\"\nIP_ADDRESSES=$(terraform\
        \ output instance_ip | jq -r)\n                    ssh ubuntu@${IP_ADDRESSES}\
        \ \"kubectl get pods -A\"\n                    ssh ubuntu@${IP_ADDRESSES}\
        \ \"kubectl get svc -A\""
