name: When Condition
'on':
  push:
    branches:
    - main
    - development
    - '*'
    - '!master'
  schedule:
  - cron: '1 13 * * 1-5 '
  workflow_dispatch:
jobs:
  Non-master:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Non-master
      run: echo "running on main branch"
  Development:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
    - name: Development
      run: echo "running on main development branch"
  Checkoutcode:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: DaggupatiPavan/java-web-app-docker
